# Generated by Django 4.0.5 on 2022-06-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(verbose_name='id')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('abbreviation', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='abbreviation')),
                ('sector', models.CharField(max_length=30, verbose_name='setor')),
                ('dy', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='dy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAndDividends',
            fields=[
                ('id', models.IntegerField(verbose_name='id')),
                ('abbreviation', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='abbreviation')),
                ('dy1', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='dy1')),
                ('dy3', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='dy3')),
                ('dy5', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='dy5')),
            ],
        ),
    ]
