# Generated by Django 4.0.5 on 2022-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0003_alter_companyanddividends_dy1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='dy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='price'),
        ),
    ]
