# Generated by Django 4.0.5 on 2022-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0005_alter_companyanddividends_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=60, verbose_name='setor'),
        ),
    ]
